### ISSUE TITLE
Singleton

### ISSUE THREAD

**Issue by e-stankevicius** [WebsiteBeaver/Simple-MySQLi#2]
If you made this object singleton, you could just do: SimpleMySQLi::query();

P.S. Thy not PDO?

**Comment by D-Marc1** [comment]
Hey, thanks for your interest and suggestion. I've strongly considered that actually, but I think I prefer it as is.

I chose MySQLi to utilize some of its MySQL-specific features. For instance, you can [get more info](https://github.com/WebsiteBeaver/Simple-MySQLi#update-same-values) on queries. This is useful when you update a row with the same value. There's also proper methods for freeing and closing the statement/connection (Read this for the issue with [closing the connection in PDO](http://php.net/manual/en/pdo.connections.php#114822)). I also would like to add async MySQL, as soon as they add prepared statements support. PDO doesn't have any of these things.

But I would certainly be glad to maintain a PDO version in addition if there's enough people have interest, potentially even in the same repo. It just wouldn't support all features, of course. But overall, It could have a near identical API.
