### ISSUE TITLE
How to fetch rows with AND clause?

### ISSUE THREAD

**Issue by IsaacHub** [WebsiteBeaver/Simple-MySQLi#4]
```
  $path = $obj->pathstr;
  $survey = $obj->surveyno;
  $ret = $db->select('SELECT * FROM land where polyPath = ? and surveyNo =?', [$path,$survey], ['%s']);
```
This gives me internal server error. Could someone help me? 

Without using `AND` clause, the query works. 
`$db->select('SELECT * FROM land where polyPath = ?', [$path], ['%s']);`

**Comment by D-Marc1** [comment]
It seems like you're using an older version of Simple MySQLi. You're also doing the data type part incorrectly, which should be a string, not an array.

You would do some thing like this:

    $ret = $mysqli->query("SELECT * FROM land where polyPath = ? and surveyNo =?", [$path,$survey], 'si')->fetchAll();

**Comment by IsaacHub** [comment]
That gave me the same error. But the following worked, because the select function expects the format to be an array:
```
 $ret = $db->select('SELECT * FROM land where polyPath = ? and surveyNo =?',[$path,$survey],['%s%i']);
```
